version: '3.8'

services:
  db_ggstore:
    image: postgres
    container_name: db_ggstore
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=progweb2
      - POSTGRES_DB=ggstore
    volumes:
      - pgdata:/data/postgres
  server:
    build:
      context: ./server
    container_name: api_ggstore
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    volumes:
      - ./server:/usr/app
    env_file:
      - ./.env
    links:
      - db_ggstore
    depends_on:
      - db_ggstore
  client:
    build:
      context: ./client
    container_name: client_ggstore
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./client:/usr/app
    env_file:
      - ./.env
volumes:
  pgdata:
    driver: local
